<?xml version="1.0" encoding="utf-8"?>
<workItemType xmlns:dm0="http://schemas.microsoft.com/VisualStudio/2008/DslTools/Core" dslVersion="12.0.0.0" Name="Architectural Epic" source="architecturalepic.xml" xmlns="http://schemas.microsoft.com/dsltools/WITDesigner">
  <States>
    <state Name="New">
      <Source>
        <transitionMoniker Name="/Architectural Epic/New~Active" />
        <transitionMoniker Name="/Architectural Epic/New~Resolved" />
        <transitionMoniker Name="/Architectural Epic/New~Removed" />
        <transitionMoniker Name="/Architectural Epic/New~Closed" />
      </Source>
      <fields>
        <stateFieldConstraint Id="0e5312c5-2161-4379-9b67-b05333f53552" ruleTag="- ">
          <fieldMoniker Name="/Architectural Epic/Resolved Date" />
        </stateFieldConstraint>
        <stateFieldConstraint Id="90f39658-2c7c-4f07-8edd-c1540609ff03" ruleTag="- ">
          <fieldMoniker Name="/Architectural Epic/Resolved By" />
        </stateFieldConstraint>
        <stateFieldConstraint Id="420dbb3a-d99c-4e36-a3af-6d523feea995" ruleTag="- ">
          <fieldMoniker Name="/Architectural Epic/Closed Date" />
        </stateFieldConstraint>
        <stateFieldConstraint Id="1e51e3b3-8985-4d08-9472-31b70ba71351" ruleTag="- ">
          <fieldMoniker Name="/Architectural Epic/Closed By" />
        </stateFieldConstraint>
        <stateFieldConstraint Id="e7f80827-d43b-489f-a8cc-077fa5ac2758" ruleTag="- ">
          <fieldMoniker Name="/Architectural Epic/Activated Date" />
        </stateFieldConstraint>
        <stateFieldConstraint Id="026abd3e-1d43-4246-8956-009d97e96149" ruleTag="- ">
          <fieldMoniker Name="/Architectural Epic/Activated By" />
        </stateFieldConstraint>
      </fields>
    </state>
    <state Name="Active">
      <Source>
        <transitionMoniker Name="/Architectural Epic/Active~New" />
        <transitionMoniker Name="/Architectural Epic/Active~Resolved" />
        <transitionMoniker Name="/Architectural Epic/Active~Closed" />
      </Source>
      <fields>
        <stateFieldConstraint Id="fc7e1549-07f4-41ca-9092-bdab222a72d5" ruleTag="- ">
          <fieldMoniker Name="/Architectural Epic/Resolved Date" />
        </stateFieldConstraint>
        <stateFieldConstraint Id="bb3df1e1-e1a4-4f40-ad3f-0c8248e39388" ruleTag="- ">
          <fieldMoniker Name="/Architectural Epic/Resolved By" />
        </stateFieldConstraint>
        <stateFieldConstraint Id="81908267-6471-40ad-a879-aa919dff3ddd" ruleTag="- ">
          <fieldMoniker Name="/Architectural Epic/Closed Date" />
        </stateFieldConstraint>
        <stateFieldConstraint Id="509ef717-055d-4abd-a4b1-9276d89fb130" ruleTag="- ">
          <fieldMoniker Name="/Architectural Epic/Closed By" />
        </stateFieldConstraint>
      </fields>
    </state>
    <state Name="Resolved">
      <Source>
        <transitionMoniker Name="/Architectural Epic/Resolved~Closed" />
        <transitionMoniker Name="/Architectural Epic/Resolved~Active" />
        <transitionMoniker Name="/Architectural Epic/Resolved~New" />
      </Source>
      <fields>
        <stateFieldConstraint Id="ca1203d3-c7f7-45ea-a1e0-421b1a975aad" ruleTag="- ">
          <fieldMoniker Name="/Architectural Epic/Closed Date" />
        </stateFieldConstraint>
        <stateFieldConstraint Id="059c0f1a-49f4-44f9-af82-5eaebb8bed78" ruleTag="- ">
          <fieldMoniker Name="/Architectural Epic/Closed By" />
        </stateFieldConstraint>
      </fields>
    </state>
    <state Name="Closed">
      <Source>
        <transitionMoniker Name="/Architectural Epic/Closed~Active" />
        <transitionMoniker Name="/Architectural Epic/Closed~Resolved" />
        <transitionMoniker Name="/Architectural Epic/Closed~New" />
      </Source>
      <fields>
        <stateFieldConstraint Id="c1c5c82b-a50a-4acb-b4f3-7bd54db50a5a" ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Business Value" />
        </stateFieldConstraint>
      </fields>
    </state>
    <state Name="Removed">
      <Source>
        <transitionMoniker Name="/Architectural Epic/Removed~New" />
      </Source>
    </state>
  </States>
  <Fields>
    <field Name="Activated By" referenceName="Microsoft.VSTS.Common.ActivatedBy" />
    <field Name="Activated Date" referenceName="Microsoft.VSTS.Common.ActivatedDate" />
    <field Name="Assigned To" referenceName="System.AssignedTo" />
    <field Name="Resolved Date" referenceName="Microsoft.VSTS.Common.ResolvedDate" />
    <field Name="Resolved By" referenceName="Microsoft.VSTS.Common.ResolvedBy" />
    <field Name="Closed Date" referenceName="Microsoft.VSTS.Common.ClosedDate" />
    <field Name="Closed By" referenceName="Microsoft.VSTS.Common.ClosedBy" />
    <field Name="Business Value" referenceName="Microsoft.VSTS.Common.BusinessValue" />
  </Fields>
  <Transitions>
    <transition Id="fa9f571a-f2cf-448b-accd-299324c7ac45" Name="~New">
      <Target>
        <stateMoniker Name="/Architectural Epic/New" />
      </Target>
      <Reasons>
        <reason Name="New" />
      </Reasons>
    </transition>
    <transition Id="450f95ba-3b28-4ca2-92a4-b09fef8f6130" Name="New~Active">
      <Target>
        <stateMoniker Name="/Architectural Epic/Active" />
      </Target>
      <Reasons>
        <reason Name="Implementation started" />
      </Reasons>
      <fields>
        <transitionFieldConstraint ruleTag="+* ">
          <fieldMoniker Name="/Architectural Epic/Activated By" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Activated Date" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Assigned To" />
        </transitionFieldConstraint>
      </fields>
    </transition>
    <transition Id="eb31258f-0556-4bfc-bf5f-1350b2e8d141" Name="New~Resolved">
      <Target>
        <stateMoniker Name="/Architectural Epic/Resolved" />
      </Target>
      <Reasons>
        <reason Name="Stories complete" />
      </Reasons>
      <fields>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Activated Date" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Activated By" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Assigned To" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Resolved Date" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="+* ">
          <fieldMoniker Name="/Architectural Epic/Resolved By" />
        </transitionFieldConstraint>
      </fields>
    </transition>
    <transition Id="cce613ee-ba0b-4bbb-8bb0-efb2c930bdea" Name="New~Removed">
      <Target>
        <stateMoniker Name="/Architectural Epic/Removed" />
      </Target>
      <Reasons>
        <reason Name="Removed from the backlog" />
      </Reasons>
    </transition>
    <transition Id="027fbcd5-f507-4007-af2e-db93053c503a" Name="Active~New">
      <Target>
        <stateMoniker Name="/Architectural Epic/New" />
      </Target>
      <Reasons>
        <reason Name="Implementation halted" />
        <reason Name="Moved to the backlog" />
      </Reasons>
    </transition>
    <transition Id="fd5fe399-9c81-42f8-8a34-7a13238ad421" Name="Active~Resolved">
      <Target>
        <stateMoniker Name="/Architectural Epic/Resolved" />
      </Target>
      <Reasons>
        <reason Name="Stories complete" />
      </Reasons>
      <fields>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Activated Date" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Activated By" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Resolved Date" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="+* ">
          <fieldMoniker Name="/Architectural Epic/Resolved By" />
        </transitionFieldConstraint>
      </fields>
    </transition>
    <transition Id="021114db-03c6-4dd8-ac8b-c0cde203b821" Name="Resolved~Closed">
      <Target>
        <stateMoniker Name="/Architectural Epic/Closed" />
      </Target>
      <Reasons>
        <reason Name="Acceptance tests pass" />
      </Reasons>
      <fields>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Activated Date" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Activated By" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Resolved Date" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Resolved By" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Closed Date" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="+* ">
          <fieldMoniker Name="/Architectural Epic/Closed By" />
        </transitionFieldConstraint>
      </fields>
    </transition>
    <transition Id="52ce6d81-4831-43a8-8d96-9f1e11f0e99e" Name="Resolved~Active">
      <Target>
        <stateMoniker Name="/Architectural Epic/Active" />
      </Target>
      <Reasons>
        <reason Name="Acceptance tests fail" />
      </Reasons>
      <fields>
        <transitionFieldConstraint ruleTag="+* ">
          <fieldMoniker Name="/Architectural Epic/Activated By" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Activated Date" />
        </transitionFieldConstraint>
      </fields>
    </transition>
    <transition Id="14b679e0-df1e-4c38-b419-b8c5c28045fa" Name="Active~Closed">
      <Target>
        <stateMoniker Name="/Architectural Epic/Closed" />
      </Target>
      <Reasons>
        <reason Name="Abandoned" />
        <reason Name="Out of scope" />
        <reason Name="Rejected" />
        <reason Name="Acceptance tests pass" />
      </Reasons>
      <fields>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Activated Date" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Activated By" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Resolved Date" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Resolved By" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Closed Date" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="+* ">
          <fieldMoniker Name="/Architectural Epic/Closed By" />
        </transitionFieldConstraint>
      </fields>
    </transition>
    <transition Id="da9273b8-0c1e-46c5-b1fe-80410b596b6d" Name="Closed~Active">
      <Target>
        <stateMoniker Name="/Architectural Epic/Active" />
      </Target>
      <Reasons>
        <reason Name="Closed in error" />
        <reason Name="Reintroduced in Scope" />
      </Reasons>
      <fields>
        <transitionFieldConstraint ruleTag="+* ">
          <fieldMoniker Name="/Architectural Epic/Activated By" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Activated Date" />
        </transitionFieldConstraint>
      </fields>
    </transition>
    <transition Id="a6303ac8-41d7-435b-adca-3c519432bf4a" Name="Closed~Resolved">
      <Target>
        <stateMoniker Name="/Architectural Epic/Resolved" />
      </Target>
      <Reasons>
        <reason Name="Closed in error" />
      </Reasons>
      <fields>
        <transitionFieldConstraint ruleTag="+* ">
          <fieldMoniker Name="/Architectural Epic/Activated By" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Activated Date" />
        </transitionFieldConstraint>
      </fields>
    </transition>
    <transition Id="a3d3ffc3-aec4-410a-9132-790887852351" Name="Removed~New">
      <Target>
        <stateMoniker Name="/Architectural Epic/New" />
      </Target>
      <Reasons>
        <reason Name="Reconsidering the epic" />
      </Reasons>
    </transition>
    <transition Id="42ad6753-fad9-452a-aec5-1fe97c043aa0" Name="Resolved~New">
      <Target>
        <stateMoniker Name="/Architectural Epic/New" />
      </Target>
      <Reasons>
        <reason Name="Moved to the backlog" />
      </Reasons>
    </transition>
    <transition Id="2f78818e-70fe-4c73-8636-12d81d13072c" Name="Closed~New">
      <Target>
        <stateMoniker Name="/Architectural Epic/New" />
      </Target>
      <Reasons>
        <reason Name="Moved to the backlog" />
      </Reasons>
    </transition>
    <transition Id="8d3213e7-a645-4b44-a2fd-b2e28872e23d" Name="New~Closed">
      <Target>
        <stateMoniker Name="/Architectural Epic/Closed" />
      </Target>
      <Reasons>
        <reason Name="Acceptance tests pass" />
      </Reasons>
      <fields>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Activated Date" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Activated By" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Resolved Date" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Resolved By" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Closed Date" />
        </transitionFieldConstraint>
        <transitionFieldConstraint ruleTag="* ">
          <fieldMoniker Name="/Architectural Epic/Closed By" />
        </transitionFieldConstraint>
      </fields>
    </transition>
  </Transitions>
</workItemType>