<?xml version="1.0" encoding="utf-8"?><workItemType dslVersion="12.0.0.0" Name="User Story" source="D:\vs_andrewclear\SAFeProcessTemplate\SAFe Process Template\WorkItem Tracking\TypeDefinitions\UserStory.xml" xmlns="http://schemas.microsoft.com/dsltools/WITDesigner" />